# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libmagick++-dev
r:
- 3.1
- 3.2
- 3.3
- oldrel
- release
- devel

matrix:
  include:
  - r: release
    pandoc: false
    env: PANDOC='none'
  - r: release
    pandoc_version: 1.19.2.1
    env: PANDOC='1.19'

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
